language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - NUMPY="numpy==1.7"
  - NUMPY="--upgrade numpy"
install:
  - pip install -r requirements.txt
  - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" == '2' ]]; then
      pip install mock;
    fi
  - pip install $NUMPY
  - pip freeze
script: "python setup.py test"
